mod data;

use std::sync::OnceLock;
use std::time::Instant;

// Generated by `cleave-build` from `src/kernel.cleave` at build time -- see
// `build.rs`.
include!(concat!(env!("OUT_DIR"), "/kernel_bindings.rs"));

static TRAINING_DONE: OnceLock<Instant> = OnceLock::new();

/// Called by the kernel between the last training step and the test-set
/// evaluation, so `elapsed` below covers training alone -- exactly the span
/// `bench/mnist-pytorch/mnist_bench.py` times, which stops its own clock
/// before evaluating.
#[unsafe(no_mangle)]
pub extern "C" fn training_done() {
    let _ = TRAINING_DONE.set(Instant::now());
}

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    data::init(&format!("{manifest_dir}/.cache"));

    let start = Instant::now();
    let accuracy = unsafe { train_and_evaluate(10, 0.001, 1) };
    let end = Instant::now();
    let trained = *TRAINING_DONE.get().expect("the kernel never called training_done");
    println!("test accuracy: {accuracy}");
    println!("elapsed: {:?}", trained - start);
    println!("elapsed (with evaluation): {:?}", end - start);
}
