mod data;

// Generated by `cleave-build` from `src/kernel.cleave` at build time -- see
// `build.rs`.
include!(concat!(env!("OUT_DIR"), "/kernel_bindings.rs"));

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    data::init(&format!("{manifest_dir}/.cache"));

    let start = std::time::Instant::now();
    let accuracy = unsafe { train_and_evaluate(10, 0.001, 1) };
    let elapsed = start.elapsed();
    println!("test accuracy: {accuracy}");
    println!("elapsed: {elapsed:?}");
}
