mod corpus;
mod data;

// Generated by `cleave-build` from `src/kernel.cleave` at build time (`build.rs`).
include!(concat!(env!("OUT_DIR"), "/kernel_bindings.rs"));

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    data::init(&format!("{manifest_dir}/.cache"));
    println!(
        "corpus: {} train / {} validation characters, alphabet of {}",
        data::train().len(),
        data::val().len(),
        corpus::alphabet().len()
    );
    let o = data::offset(data::train().len(), data::TRAIN_SEED, 0, 0);
    println!("first training window: {:?}", corpus::decode(&data::train()[o..o + data::T]));

    let nats = unsafe { bigram_baseline(200, 50) };
    println!("bigram baseline: {nats:.4} nats/char ({:.4} bits/char)", nats / std::f32::consts::LN_2);
}
