mod corpus;
mod data;
mod generate;

use std::sync::Mutex;
use std::time::Instant;

// Generated by `cleave-build` from `src/kernel.cleave` at build time (`build.rs`).
include!(concat!(env!("OUT_DIR"), "/kernel_bindings.rs"));

/// When the previous round ended (or training started), for `round_done`'s timings.
static ROUND: Mutex<Option<(Instant, Instant, i32)>> = Mutex::new(None);

/// Called by the kernel at the end of each training round (and once before the first): the step
/// reached, the losses, the learning rate; printed with the time per step since the last round.
#[unsafe(no_mangle)]
pub extern "C" fn round_done(step: i32, train_loss: f32, validation_loss: f32, rate: f32) {
    let now = Instant::now();
    let mut round = ROUND.lock().unwrap();
    match *round {
        None => {
            println!("step {step}: validation {validation_loss:.4}, learning rate {rate:.6}");
            *round = Some((now, now, step));
        }
        Some((start, last, last_step)) => {
            let per_step = (now - last).as_secs_f64() * 1000.0 / f64::from((step - last_step).max(1));
            println!(
                "step {step}: train {train_loss:.4}, validation {validation_loss:.4}, learning rate {rate:.6},                  {per_step:.0} ms/step, {:.1} min elapsed",
                (now - start).as_secs_f64() / 60.0
            );
            *round = Some((start, now, step));
        }
    }
}

fn main() {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let cache = format!("{manifest_dir}/.cache");
    data::init(&cache);
    // Checkpoints are written next to the corpus.
    std::env::set_current_dir(&cache).expect("cannot enter the cache directory");
    let which = std::env::args().nth(1).unwrap_or_else(|| "lm".to_string());
    if which == "gpt" || which == "bench" || which == "zola" {
        // One directory per model size: its checkpoints don't fit another size. `bench` trains
        // exactly as `gpt` does, in a directory of its own, so that a comparison run against the
        // PyTorch twin never overwrites the real run's checkpoints.
        let suffix = if which == "bench" { "-bench" } else { "" };
        let dir = format!("gpt-d{}-l{}{suffix}", unsafe { gpt_width() }, unsafe { gpt_layers() });
        std::fs::create_dir_all(&dir).expect("cannot create the model's checkpoint directory");
        std::env::set_current_dir(&dir).expect("cannot enter the model's checkpoint directory");
        eprintln!("checkpoints in .cache/{dir}");
    }
    if which != "zola" {
        println!(
            "corpus: {} train / {} validation characters, alphabet of {}",
            data::train().len(),
            data::val().len(),
            corpus::alphabet().len()
        );
        let o = data::offset(data::train().len(), data::TRAIN_SEED, 0, 0);
        println!("first training window: {:?}", corpus::decode(&data::train()[o..o + data::T]));

        let nats = unsafe { bigram_baseline(200, 50) };
        println!("bigram baseline: {nats:.4} nats/char ({:.4} bits/char)", nats / std::f32::consts::LN_2);
    }
    if which == "bigram" {
        let learned = unsafe { train_bigram(10, 0.05, 1) };
        println!("learned bigram: {learned:.4} nats/char ({:.4} bits/char)", learned / std::f32::consts::LN_2);
    } else if which == "zola" {
        // `zola "prompt" [characters [temperature [seed]]]`, with the model in `gpt.ckpt`.
        let prompt = std::env::args().nth(2).unwrap_or_default();
        let count: i32 = std::env::args().nth(3).map_or(500, |a| a.parse().expect("a character count"));
        let temperature: f32 = std::env::args().nth(4).map_or(0.8, |a| a.parse().expect("a temperature"));
        let seed: i64 = std::env::args().nth(5).map_or(1, |a| a.parse().expect("a seed"));
        let shown = generate::set_prompt(&prompt);
        print!("{shown}");
        unsafe { generate(count, temperature, seed) };
        println!();
    } else if which == "gpt" || which == "bench" {
        // `gpt [first_step [rounds [steps_per_round]]]`; a first step above 0 resumes from
        // `gpt.ckpt`.
        let arg = |i: usize, default: i32| std::env::args().nth(i).map_or(default, |a| a.parse().expect("an integer"));
        let (first, rounds, per_round) = (arg(2, 0), arg(3, 10), arg(4, 100));
        let start = std::time::Instant::now();
        let nats = unsafe { train_gpt(first, rounds, per_round, 0.001, 1, first > 0) };
        println!("transformer: {nats:.4} nats/char ({:.4} bits/char)", nats / std::f32::consts::LN_2);
        println!("elapsed: {:?}", start.elapsed());
    } else {
        let start = std::time::Instant::now();
        let nats = unsafe { train_lm(10, 0.003, 1) };
        println!("embedding + MLP: {nats:.4} nats/char ({:.4} bits/char)", nats / std::f32::consts::LN_2);
        println!("elapsed: {:?}", start.elapsed());
    }
}
