//! Generates a mechanical, scalar-only `extern "C" { ... }` Rust binding for
//! every `export fn` in a compiled program (`ast.rs`'s own `FnDecl::
//! is_export` doc comment) — the automated form of the hand-written
//! `extern "C"` block a real host-side Rust caller needs to call across the
//! `--emit-object` boundary (`main.rs`'s own `--emit-object`, which this
//! module's own `--emit-bindings` flag runs alongside). Deliberately no
//! attempt at a "safe" wrapper, ownership-aware type, or struct/tensor ABI
//! here — see this crate's own `doc/hld.md`-referenced plan for why that's a
//! separate, later step: a `Tensor`/struct argument needs a real `#[repr(C)]`
//! type design on the Rust side (matching either MLIR's own memref
//! descriptor, or this project's own opaque heap-struct-pointer convention),
//! not attempted here. A signature this module can't map is a hard,
//! reported error, not a silently-wrong or silently-skipped binding.

use crate::cps::CTopLevelFn;
use crate::infer::Ty;

/// `Ty::Con(name)` for exactly the scalar widths `cleave-rt`/`mlir_lower.rs`
/// already give a real C-ABI shape to — anything else (an array, a struct
/// via `Ty::App`, a tuple, an unresolved `Var`/`Pack`) has no mapping here.
fn scalar_rust_type(ty: &Ty) -> Option<&'static str> {
    let Ty::Con(name) = ty else { return None };
    match name.as_str() {
        "i8" => Some("i8"),
        "i16" => Some("i16"),
        "i32" => Some("i32"),
        "i64" => Some("i64"),
        "f32" => Some("f32"),
        "f64" => Some("f64"),
        "bool" => Some("bool"),
        _ => None,
    }
}

fn is_unit(ty: &Ty) -> bool {
    matches!(ty, Ty::Con(name) if name == "()")
}

/// One `export fn`'s own signature, once every scalar type in it has
/// resolved cleanly — `None`'s own reporting happens at the call site
/// (`generate_rust_bindings`), which has the function's own name on hand for
/// a useful message; this function only decides shape, not phrasing.
struct ExportedSignature<'a> {
    symbol: &'a str,
    param_types: Vec<&'static str>,
    ret_type: Option<&'static str>,
}

fn resolve_signature(f: &CTopLevelFn) -> Result<ExportedSignature<'_>, String> {
    let symbol = f.export_symbol.as_deref().unwrap_or(&f.def.name);
    let mut param_types = Vec::with_capacity(f.param_types.len());
    for (i, ty) in f.param_types.iter().enumerate() {
        match scalar_rust_type(ty) {
            Some(rust_ty) => param_types.push(rust_ty),
            None => {
                return Err(format!(
                    "export fn `{}` (symbol `{symbol}`): parameter {i} has type `{ty}`, which isn't a supported scalar \
                     (only i8/i16/i32/i64/f32/f64/bool cross this boundary today — struct/array/tensor export bindings \
                     aren't implemented yet)",
                    f.def.name
                ));
            }
        }
    }
    let ret_type = if is_unit(&f.result) {
        None
    } else {
        match scalar_rust_type(&f.result) {
            Some(rust_ty) => Some(rust_ty),
            None => {
                return Err(format!(
                    "export fn `{}` (symbol `{symbol}`): return type `{}` isn't a supported scalar \
                     (only i8/i16/i32/i64/f32/f64/bool cross this boundary today — struct/array/tensor export bindings \
                     aren't implemented yet)",
                    f.def.name, f.result
                ));
            }
        }
    };
    Ok(ExportedSignature {
        symbol,
        param_types,
        ret_type,
    })
}

/// Every `export fn` reachable in `funcs` (ordinarily a `CpsProgram::funcs`
/// already past dead-code elimination — see `main.rs`'s own `--emit-
/// bindings` wiring), rendered as one `extern "C" { fn ...; }` Rust source
/// file. `Err` lists every signature this module can't map, not just the
/// first — a real compile-time report, not a panic on the first offender.
pub fn generate_rust_bindings<'a>(
    funcs: impl IntoIterator<Item = &'a CTopLevelFn>,
) -> Result<String, Vec<String>> {
    let mut signatures = Vec::new();
    let mut errors = Vec::new();
    for f in funcs {
        if !f.is_export {
            continue;
        }
        match resolve_signature(f) {
            Ok(sig) => signatures.push(sig),
            Err(e) => errors.push(e),
        }
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    signatures.sort_by(|a, b| a.symbol.cmp(b.symbol));

    let mut out = String::new();
    out.push_str("// Generated by `cleave --emit-bindings` -- do not edit by hand.\n\n");
    // `unsafe extern "C"` -- required by the 2024 edition (the plain
    // `extern "C" { ... }` this used to emit only still compiles under an
    // older edition; every crate in this workspace is already 2024, and so
    // is any real consumer likely to be going forward, found by direct
    // testing against `examples/rust-interop-demo`). Individual fn items
    // stay ordinary `pub fn` (not `pub safe fn`, 2024's own opt-in to make
    // a binding callable outside `unsafe { ... }`) -- unchanged, still only
    // callable from an `unsafe` block at the use site, matching this
    // module's existing scalar-only, no-safety-wrapper posture.
    out.push_str("unsafe extern \"C\" {\n");
    for sig in &signatures {
        let params = sig
            .param_types
            .iter()
            .enumerate()
            .map(|(i, ty)| format!("a{i}: {ty}"))
            .collect::<Vec<_>>()
            .join(", ");
        match sig.ret_type {
            Some(ret) => out.push_str(&format!("    pub fn {}({params}) -> {ret};\n", sig.symbol)),
            None => out.push_str(&format!("    pub fn {}({params});\n", sig.symbol)),
        }
    }
    out.push_str("}\n");
    Ok(out)
}
