<#
Downloads (or reuses) the prebuilt LLVM 22 + MLIR + openmp toolchain
`cleave-llvm-redist` publishes, and writes `.cargo/config.toml` (gitignored,
machine-specific -- see `.cargo/config.toml.example`) so `mlir-sys`/
`tblgen-rs`/`cleave-mlir-shim`'s own build scripts pick it up automatically.

Replaces the previous "set MLIR_SYS_220_PREFIX/TABLEGEN_220_PREFIX by hand
in your shell profile, restart your shell, hope you remembered on the next
machine" step (`doc/building.md`'s own real bug history: a machine-specific
path hardcoded into a *tracked* `.cargo/config.toml` once broke every other
machine, CI included) with one idempotent command -- run identically by a
fresh dev machine, CI (`.github/workflows/ci.yml`), and anyone re-pointing
at a version bump.

Usage:
  scripts/setup-toolchain.ps1                                    # download/cache the pinned release (ci/toolchain-version.txt)
  scripts/setup-toolchain.ps1 -Force                             # re-download even if the cache already looks current
  scripts/setup-toolchain.ps1 -ExistingPrefix C:\llvm-mlir-22    # point at an already-built local toolchain instead -- no download
#>
param(
    # `target\` -- not `%LOCALAPPDATA%` -- deliberately: this repo (and
    # therefore `target\`) commonly lives on a separate dev drive from the
    # OS drive, and a 1GB+ toolchain has no business sitting on the system
    # disk just because that's the ordinary place for a per-user cache.
    # `target\` is already gitignored (`/target`), and `cargo clean`
    # deleting it along with the rest of the build output (re-downloading
    # rather than rebuilding from source) is an accepted, deliberate
    # trade-off here, not an oversight.
    [string]$CacheDir = (Join-Path $PSScriptRoot "..\target\llvm-mlir-22"),
    [string]$ExistingPrefix = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
# `Invoke-WebRequest`'s own progress-bar rendering is notoriously slow on a
# multi-hundred-MB archive under Windows PowerShell 5.1 -- this is the
# documented workaround, not a cosmetic choice.
$ProgressPreference = "SilentlyContinue"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$cargoConfigPath = Join-Path $repoRoot ".cargo\config.toml"

function Write-CleaveCargoConfig([string]$Prefix) {
    $forward = $Prefix -replace '\\', '/'
    New-Item -ItemType Directory -Force -Path (Split-Path $cargoConfigPath) | Out-Null
    $content = @"
# Generated by scripts/setup-toolchain.ps1 -- gitignored, machine-specific,
# safe to delete and regenerate. Do not hand-edit or commit (see
# .cargo/config.toml.example for the tracked, path-free explanation of what
# this is). Re-run the script after a toolchain version bump
# (ci/toolchain-version.txt) to refresh it.
[env]
MLIR_SYS_220_PREFIX = "$forward"
TABLEGEN_220_PREFIX = "$forward"
"@
    Set-Content -Path $cargoConfigPath -Value $content -Encoding utf8
    Write-Host "Wrote $cargoConfigPath -> $Prefix"
}

if ($ExistingPrefix -ne "") {
    $probe = Join-Path $ExistingPrefix "bin\mlir-opt.exe"
    if (-not (Test-Path $probe)) {
        throw "-ExistingPrefix '$ExistingPrefix' doesn't look like a real LLVM/MLIR install (no bin\mlir-opt.exe under it)"
    }
    Write-CleaveCargoConfig $ExistingPrefix
} else {
    $onWindows = ([System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT)
    if (-not $onWindows) {
        throw "setup-toolchain.ps1: cleave-llvm-redist has no prebuilt release for this platform yet (Windows/MSVC only today -- a Linux build is planned; until then, build LLVM from source per doc/building.md's own fallback section)."
    }

    $tagFile = Join-Path $repoRoot "ci\toolchain-version.txt"
    $tag = (Get-Content $tagFile | Select-Object -First 1).Trim()
    # Only "windows-msvc" exists today -- cleave-llvm-redist's own build-
    # release workflow is Windows-only so far (its own header comment says
    # so). A Linux job there will add a second asset (naming convention not
    # settled yet); this is the one line that'll need to branch on the host
    # OS once it does.
    $platform = "windows-msvc"
    $asset = "llvm-mlir-22-$platform.zip"
    $url = "https://github.com/doomtr666/cleave-llvm-redist/releases/download/$tag/$asset"
    $marker = Join-Path $CacheDir ".cleave-toolchain-version"

    $upToDate = $false
    if ((-not $Force) -and (Test-Path $marker)) {
        $existingTag = (Get-Content $marker | Select-Object -First 1).Trim()
        if ($existingTag -eq $tag) {
            $upToDate = $true
        }
    }

    if ($upToDate) {
        Write-Host "cleave toolchain $tag already cached at $CacheDir"
    } else {
        Write-Host "Downloading cleave toolchain $tag ($asset)..."
        New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null
        Get-ChildItem -Path $CacheDir -Force | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        $zipPath = Join-Path ([System.IO.Path]::GetTempPath()) $asset
        Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing
        Expand-Archive -Path $zipPath -DestinationPath $CacheDir -Force
        Remove-Item $zipPath -Force
        Set-Content -Path $marker -Value $tag
        Write-Host "Installed cleave toolchain $tag to $CacheDir"
    }

    Write-CleaveCargoConfig $CacheDir
}
