<#
Downloads (or reuses) the prebuilt OpenBLAS toolchain `cleave-openblas-redist`
publishes. Running this with no arguments is normally *all* that's needed --
`cleave-rt` loads `openblas.dll` explicitly at runtime (`LoadLibraryW`, not an
ordinary implicit link -- `cleave-rt/Cargo.toml`'s own doc comment), from a
path baked in at compile time (`<this repo>/target/openblas`, this script's
own default `-CacheDir`) -- no `PATH`/env var/manual DLL copy needed for the
common case, on *any* process (`cleave.exe`, any "-interop" example, even
that example's own build script).

Also merges an `OPENBLAS_PREFIX` entry into `.cargo/config.toml` (gitignored,
machine-specific -- see `scripts/setup-toolchain.ps1`'s own identical
convention for LLVM/MLIR) as an optional *override* for a non-default
install location (`-ExistingPrefix`, below) -- real, but only takes effect
for a process cargo itself spawns (`cargo run`/`cargo test`), since it's an
ordinary process environment variable, not a system-wide one. A standalone
`.exe` run outside cargo, pointed at a non-default OpenBLAS install, needs a
real `OPENBLAS_PREFIX` set some other way (a shell profile, a launch script).

Merges into the existing `[env]` block rather than overwriting it outright --
`setup-toolchain.ps1` may already have written `CLEAVE_LLVM_PREFIX` into the very same file, and both scripts need to
coexist there.

Usage:
  scripts/setup-openblas.ps1                                       # download/cache the pinned release (ci/openblas-version.txt)
  scripts/setup-openblas.ps1 -Force                                # re-download even if the cache already looks current
  scripts/setup-openblas.ps1 -ExistingPrefix I:\openblas-windows   # point at an already-built/extracted local layout instead -- no download
#>
param(
    # Same reasoning as `setup-toolchain.ps1`'s own `$CacheDir` default --
    # `target\` (already gitignored), not `%LOCALAPPDATA%`, so a multi-drive
    # dev setup never has this land on the wrong disk.
    [string]$CacheDir = (Join-Path $PSScriptRoot "..\target\openblas"),
    [string]$ExistingPrefix = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$cargoConfigPath = Join-Path $repoRoot ".cargo\config.toml"

function Merge-CleaveCargoConfigEnv([hashtable]$NewEntries) {
    $entries = [ordered]@{}
    if (Test-Path $cargoConfigPath) {
        $inEnv = $false
        foreach ($line in Get-Content $cargoConfigPath) {
            $trimmed = $line.Trim()
            if ($trimmed -eq "[env]") { $inEnv = $true; continue }
            if ($trimmed.StartsWith("[") -and $trimmed -ne "[env]") { $inEnv = $false; continue }
            if ($inEnv -and ($trimmed -match '^([A-Za-z0-9_]+)\s*=\s*"(.*)"$')) {
                $entries[$Matches[1]] = $Matches[2]
            }
        }
    }
    foreach ($key in $NewEntries.Keys) {
        $entries[$key] = $NewEntries[$key]
    }
    New-Item -ItemType Directory -Force -Path (Split-Path $cargoConfigPath) | Out-Null
    $lines = @(
        "# Generated by scripts/setup-toolchain.ps1 / scripts/setup-openblas.ps1 --",
        "# gitignored, machine-specific, safe to delete and regenerate. Do not",
        "# hand-edit or commit (see .cargo/config.toml.example). Re-run the",
        "# relevant script after a toolchain/OpenBLAS version bump to refresh it.",
        "[env]"
    )
    foreach ($key in $entries.Keys) {
        $lines += "$key = `"$($entries[$key])`""
    }
    Set-Content -Path $cargoConfigPath -Value ($lines -join "`n") -Encoding utf8
    Write-Host "Wrote $cargoConfigPath"
}

function Write-OpenblasPrefix([string]$Prefix) {
    $forward = $Prefix -replace '\\', '/'
    Merge-CleaveCargoConfigEnv @{ "OPENBLAS_PREFIX" = $forward }
    Write-Host "OPENBLAS_PREFIX -> $Prefix (only needed as an override -- see this script's own top comment)"
}

if ($ExistingPrefix -ne "") {
    $probe = Join-Path $ExistingPrefix "lib\openblas.lib"
    if (-not (Test-Path $probe)) {
        throw "-ExistingPrefix '$ExistingPrefix' doesn't look like a real OpenBLAS install (no lib\openblas.lib under it)"
    }
    Write-OpenblasPrefix $ExistingPrefix
} else {
    $onWindows = ([System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT)
    if (-not $onWindows) {
        throw "setup-openblas.ps1: cleave-openblas-redist has no prebuilt release for this platform yet (Windows/MSVC only today)."
    }

    $tagFile = Join-Path $repoRoot "ci\openblas-version.txt"
    $tag = (Get-Content $tagFile | Select-Object -First 1).Trim()
    $asset = "openblas-windows-msvc.zip"
    $url = "https://github.com/doomtr666/cleave-openblas-redist/releases/download/$tag/$asset"
    $marker = Join-Path $CacheDir ".cleave-openblas-version"

    $upToDate = $false
    if ((-not $Force) -and (Test-Path $marker)) {
        $existingTag = (Get-Content $marker | Select-Object -First 1).Trim()
        if ($existingTag -eq $tag) {
            $upToDate = $true
        }
    }

    if ($upToDate) {
        Write-Host "cleave OpenBLAS $tag already cached at $CacheDir"
    } else {
        Write-Host "Downloading cleave OpenBLAS $tag ($asset)..."
        New-Item -ItemType Directory -Force -Path $CacheDir | Out-Null
        Get-ChildItem -Path $CacheDir -Force | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        $zipPath = Join-Path ([System.IO.Path]::GetTempPath()) $asset
        Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing
        Expand-Archive -Path $zipPath -DestinationPath $CacheDir -Force
        Remove-Item $zipPath -Force
        Set-Content -Path $marker -Value $tag
        Write-Host "Installed cleave OpenBLAS $tag to $CacheDir"
    }

    Write-OpenblasPrefix $CacheDir
}
