// Generated by `cleave-build` from `src/kernel.cleave` at build time -- see
// `build.rs`.
include!(concat!(env!("OUT_DIR"), "/kernel_bindings.rs"));

fn main() {
    let result = unsafe { cleave_add(17, 25) };
    println!("cleave_add(17, 25) = {result}");
    assert_eq!(result, 42);
    println!("OK");
}
